version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    ports:
      - "5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_DB=api-service
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python /api_service/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/api_service
    ports:
      - 8000:8000
    depends_on:
      - db
  
  celery:
    restart: always
    build: .
    command: celery -A api_service worker -l INFO
    volumes:
      - .:/api_service
    depends_on:
      - web
      - rabbitmq3

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672


volumes:
  postgres_data:
