# Generated by Django 5.0.1 on 2024-02-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
    ]
