# Generated by Django 5.0.1 on 2024-02-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20240223_1442'),
    ]

    operations = [
    ]
