name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    # setup heroku cli
    - name: Setup Heroku CLI
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: studious-couscous
        heroku_email: mmasabacollins9@gmail.com

    - name: Login to Heroku Container Registry
      run: docker login --username=cmmasaba --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

    - name: Build and push Docker image
      run: |
        docker build -t registry.heroku.com/studious-couscous/web .
        docker push registry.heroku.com/studious-couscous/web

    - name: Release to Heroku
      run: |
        heroku container:release web --app studious-couscous